const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.wrap,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Cnds.CompareWidth
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Sine: 0},
	{start_game: 0},
	{Touch: 0},
	{tb_game3: 0},
	{cat: 0},
	{Solid: 0},
	{tb_ground: 0},
	{start_page: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Wrap: 0},
	{behavior: 0},
	{tb_bush: 0},
	{tb_mode: 0},
	{tm: 0},
	{tm2: 0},
	{tm3: 0},
	{tm4: 0},
	{trees: 0},
	{trees2: 0},
	{"1kan": 0},
	{Score1: 0},
	{game1: 0},
	{bg_text: 0},
	{bg_dark: 0},
	{X: 0},
	{game_one: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Physics: 0},
	{"2kan": 0},
	{Sprite: 0},
	{slicelengthX: 0},
	{slicelengthY: 0},
	{Fade: 0},
	{Slice: 0},
	{blackbox: 0},
	{Splash: 0},
	{Score2: 0},
	{game2: 0},
	{Tween: 0},
	{fade: 0},
	{tb_game2: 0},
	{game_two: 0},
	{tb_ground3: 0},
	{cannon: 0},
	{cannon2: 0},
	{ball: 0},
	{game3: 0},
	{box2: 0},
	{Particles: 0},
	{Game: 0},
	{Mode_text: 0},
	{bg_loadscreen: 0},
	{bg_screen: 0},
	{load_bar: 0},
	{complete: 0},
	{bg_win: 0},
	{loading: 0},
	{"3kan": 0},
	{"3kan1": 0},
	{smntara: 0},
	{bgback: 0},
	{LocalStorage: 0},
	{game2_highscore: 0},
	{"1kan1": 0},
	{"1kan2": 0},
	{"1kan3": 0},
	{"1kan4": 0},
	{"1kan5": 0},
	{"1kan6": 0},
	{Setting: 0},
	{"2bom": 0},
	{bg_setting: 0},
	{setting_home: 0},
	{setting_resume: 0},
	{setting_replay: 0},
	{setting_sound: 0},
	{Setting2: 0},
	{setting_dark: 0},
	{Timer3: 0},
	{Round3: 0},
	{game2_score: 0},
	{lose_dark: 0},
	{scorebg: 0},
	{Game_Over: 0},
	{win_text: 0},
	{blackbox2: 0},
	{Timer4: 0},
	{canon2: 0},
	{spawn2: 0},
	{ikan2: 0},
	{canon3: 0},
	{spawn3: 0},
	{ikan3: 0},
	{playSound: 0},
	{fish: 0},
	{isMuted: 0},
	{lastX: 0},
	{lastY: 0},
	{IsX: 0},
	{Score: 0},
	{GameOver: 0},
	{Highscore: 0},
	{CanSpawn: 0},
	{canon1: 0},
	{RoundGame: 0},
	{GameStart: 0},
	{Timer: 0},
	{spawn: 0},
	{isAtkCannon: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	start_game: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	tb_game3: class extends self.ITiledBackgroundInstance {},
	cat: class extends self.ISpriteInstance {},
	tb_ground: class extends self.ITiledBackgroundInstance {},
	start_page: class extends self.ITiledBackgroundInstance {},
	behavior: class extends self.ISpriteInstance {},
	tb_bush: class extends self.ITiledBackgroundInstance {},
	tb_mode: class extends self.ISpriteInstance {},
	tm: class extends self.ISpriteInstance {},
	tm2: class extends self.ISpriteInstance {},
	tm3: class extends self.ISpriteInstance {},
	tm4: class extends self.ISpriteInstance {},
	trees: class extends self.ISpriteInstance {},
	trees2: class extends self.ISpriteInstance {},
	_1kan: class extends self.ISpriteInstance {},
	Score1: class extends self.ITextInstance {},
	game1: class extends self.ITextInstance {},
	bg_text: class extends self.ISpriteInstance {},
	bg_dark: class extends self.ITiledBackgroundInstance {},
	X: class extends self.ITextInstance {},
	game_one: class extends self.ISpriteInstance {},
	_2kan: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Slice: class extends self.ISpriteInstance {},
	blackbox: class extends self.ISpriteInstance {},
	Splash: class extends self.ISpriteInstance {},
	Score2: class extends self.ITextInstance {},
	game2: class extends self.ITextInstance {},
	fade: class extends self.ISpriteInstance {},
	tb_game2: class extends self.ITiledBackgroundInstance {},
	game_two: class extends self.ISpriteInstance {},
	tb_ground3: class extends self.ITiledBackgroundInstance {},
	cannon: class extends self.ISpriteInstance {},
	cannon2: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	game3: class extends self.ITextInstance {},
	box2: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Game: class extends self.ISpriteInstance {},
	Mode_text: class extends self.ISpriteInstance {},
	bg_loadscreen: class extends self.ISpriteInstance {},
	bg_screen: class extends self.ISpriteInstance {},
	load_bar: class extends self.ITiledBackgroundInstance {},
	complete: class extends self.ITextInstance {},
	bg_win: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	_3kan: class extends self.ISpriteInstance {},
	_3kan1: class extends self.ISpriteInstance {},
	smntara: class extends self.ISpriteInstance {},
	bgback: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	game2_highscore: class extends self.ITextInstance {},
	_1kan1: class extends self.ISpriteInstance {},
	_1kan2: class extends self.ISpriteInstance {},
	_1kan3: class extends self.ISpriteInstance {},
	_1kan4: class extends self.ISpriteInstance {},
	_1kan5: class extends self.ISpriteInstance {},
	_1kan6: class extends self.ISpriteInstance {},
	Setting: class extends self.ISpriteInstance {},
	_2bom: class extends self.ISpriteInstance {},
	bg_setting: class extends self.ISpriteInstance {},
	setting_home: class extends self.ISpriteInstance {},
	setting_resume: class extends self.ISpriteInstance {},
	setting_replay: class extends self.ISpriteInstance {},
	setting_sound: class extends self.ISpriteInstance {},
	Setting2: class extends self.ISpriteInstance {},
	setting_dark: class extends self.ITiledBackgroundInstance {},
	Timer3: class extends self.ITextInstance {},
	Round3: class extends self.ITextInstance {},
	game2_score: class extends self.ITextInstance {},
	lose_dark: class extends self.ITiledBackgroundInstance {},
	scorebg: class extends self.ISpriteInstance {},
	Game_Over: class extends self.ITextInstance {},
	win_text: class extends self.ITextInstance {},
	blackbox2: class extends self.ISpriteInstance {},
	Timer4: class extends self.ITextInstance {}
}